version: "3.8"

services:
  redis:
    image: redis:7.2
    container_name: redis_local
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/data
    networks:
      - backend-network
    expose:
      - "6379"

networks:
  backend-network:
    driver: bridge

